server:
  port: 18081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.222:9527
        namespace: tianyan-cloud
  datasource:
    url: jdbc:mysql://192.168.136.34/newland_cloud_oauth?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: cloud
    password: Cloud@Algo_db1
    driver-class-name: com.mysql.cj.jdbc.Driver
    management-app:
      username: cloud
      password: Cloud@Algo_db1
      jdbc-url: jdbc:mysql://192.168.136.34/newland_cloud_management_app?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    account:
      username: cloud
      password: Cloud@Algo_db1
      jdbc-url: jdbc:mysql://192.168.136.34/newland_cloud_oauth?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization:
      FAIL_ON_EMPTY_BEANS: false
logging:
  level:
    org.springframework.security: error


