spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.2.140:18081/rsa/publicKey

log-dir: H:\framework\hzsy\hzsy-api\logs\gateway-service