server:
  port: 18080

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    #注册中心
    nacos:
      discovery:
        server-addr: 192.168.136.222:9527
        namespace: tianyan-cloud
    #远程调用
    feign:
      client:
        config:
          auth-service:
            connectTimeout: 120000
            readTimeout: 30000
    #json
    jackson:
      property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES #驼峰转小写下划线
      serialization:
        FAIL_ON_EMPTY_BEANS: false
      main:
        allow-bean-definition-overriding: true
#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.newland.tianyan.face.domain
#oauth
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      jwt:
        key-uri: http://localhost:18081/oauth/token_key #这里的IP和端口是auth-cloud服务的IP和端口
#swagger
swagger:
  enabled: false
#日志
log-dir: H:\yexj\tianyan-cloud\tianyan-cloud-api-service\logs

user:
  id: ohhhhhh,I'm primary,just for test~

