server:
  port: 6060
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.222:9527
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          filters:
            - StripPrefix=2
          predicates:
            - Path=/cloudService/auth-cloud/oauth/token
        - id: face-service
          uri: lb://face-service
          filters:
            - StripPrefix=2
          predicates:
            - Path=/cloudService/ncsms/backend/**,/cloudService/ncsms/face/**


log-dir: H:\framework\hzsy\hzsy-api\logs\gateway-service