server:
  port: 18083

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.222:9527
        namespace: tianyan-cloud
milvus:
  host: 192.168.136.222
  port: 19540
  nprobe: 1024

log-dir: H:\tianyan\logs\vector-search-service