server:
  port: 18888

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.222:9527
        namespace: tianyan-cloud
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/oauth/token
        - id: face-service
          uri: lb://face-service
          predicates:
            - Path=/backend/**,/face/**


log-dir: H:\framework\hzsy\hzsy-api\logs\gateway-service