server:
  port: 8888

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.222:9527
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: face-service
          uri: lb://face-service
          predicates:
            - Path=/backend/**