#server:
#  port: 18085
#
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.136.222:9527
#          namespace: tianyan-cloud
#
#fdfs:
#  so-timeout: 1500
#  connect-timeout: 600
#  pool:
#    jmx-enabled: false
#  thumb-image:
#    width: 100
#    height: 100
#  tracker-list: 192.168.136.222:22122