#server:
#  port: 18085
#
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.136.222:9527
#        namespace: tianyan-cloud
#  jackson:
#    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
#
#
#fdfs:
#  so-timeout: 1500
#  connect-timeout: 600
#  pool:
#    jmx-enabled: false
#  thumb-image:
#    width: 100
#    height: 100
#  tracker-list: 192.168.136.222:22122

log-dir: H:\framework\hzsy\hzsy-api\logs\image-store-service