spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false